title: Alexander Lor
# logo: /assets/img/headshot.png
description: Education Technologist in Higher Education
show_downloads: true
theme: jekyll-theme-minimal
# theme: jekyll-theme-merlot
# theme: jekyll-theme-slate
